title: James Alfei
baseurl: ""
tagline: The personal website of James Alfei
url: "https://jamesalfei.co.uk"
description: >
  The personal website of James Alfei.
show_excerpts: true

minima-jamesalfei:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  jamesalfei
    # devto: jekyll
    # dribbble: jekyll
    facebook: jamesalfei
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: jamesalfei
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima-jamesalfei

plugins:
  - jekyll-feed
  - jekyll-seo-tag

port: 4001
