---
title: JNX.wales
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "page"
    values:
      layout: "page"
author:
  name: Jake Jenkins
  email: dev@jakejnx.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
show_excerpts: false
minima:
  date_format: "%-d %b, %Y"
  social_links:
    twitter: jakejnx
    github: jakejnx
theme: minima
plugins:
- jekyll-seo-tag
