title: KOSPI Forecast
author:
  name: lbk
  email: lbk209@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  A new post will be created when KOSPI[kospi](https://en.wikipedia.org/wiki/KOSPI) is predicted to rise next month.
  The Prediction is made by a gradient boosting machine fit on historical data
  such as KOSPI, commodities and interest rates.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  lbk209
    blogger: leebaekku
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

gem "github-pages", "~> 225", group: :jekyll_plugins

url: https://lbk209.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /kospi      # place folder name if the site is served in a subfolder
